version: '3'
services:
  api:
    build:
      context: ./app-api
      dockerfile: ./docker/Dockerfile
    container_name: app_service
    ports:
     - 8081:8080
     - 5081:5080
    links:
     - db:dbserver
    entrypoint: ["./scripts/wait-for-it.sh", "dbserver:8080", "--timeout=0", "--strict", "--", "java", "-Xdebug", "-Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=5080", "-Dserver.port=8080", "-jar", "app-api-0.0.1-SNAPSHOT.jar"]
  db:
    build: ./app-shared/docker
    image: app-db
    container_name: app_db
    ports:
     - 41521:1521
     - 48080:8080
  